// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmtwmkfaxucssflcufkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtdHdta2ZheHVjc3NmbGN1ZmtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODA1OTgsImV4cCI6MjA3MDA1NjU5OH0.ajrG87loV3xqr2M1UHBGU4Ti8rBq7FysaQ4NOVrh_Ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});